language: php

php:
  #- 5.3
  #- 5.4
  #- 5.5
  #- 5.6
  #- 7.0
  - 7.1
  #- hhvm

#matrix:
  #allow_failures:
    #- php: 7.0
    #- php: hhvm
  #include:
    #- php: 5.4
    #  env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - vendor/bin/phpunit

after_success:
  - bash <(curl -s https://codecov.io/bash)
